name: info_covid19
description: A new Flutter project. Created by Slidy

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fl_chart: ^0.11.1
  google_fonts: ^1.1.0
  loading_indicator: ^1.2.0
  carousel_slider: ^2.2.1
  flutter_svg: ^0.19.0
  flutter:
    sdk: flutter
  # bottom bar
  fancy_bottom_bar: ^0.0.1
  # link para navegador
  url_launcher: ^5.7.0
  #icons 
  font_awesome_flutter: ^8.8.1
  flutter_icons: ^1.1.0
  # hasura 
  hasura_connect: ^1.2.2+1  
  # cache
  shared_preferences: ^0.5.11
  # cache de image
  cached_network_image: ^2.3.2+1
  # requisição http
  dio: ^3.0.10
  dio_http_cache: ^0.2.9
  # gerenciamento de estado
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  # injeção de dependencia 
  flutter_modular: ^2.0.1
  # idioma e localização
  intl_utils: ^1.6.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.2.4
  mockito: ^4.1.1
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter
      
flutter:
  uses-material-design: true
  fonts:
      - family: Montserrat
        fonts:
            - asset: lib/app/core/assets/fonts/Montserrat.ttf

      - family: Cairo
        fonts:
            - asset: lib/app/core/assets/fonts/Cairo.ttf
  assets: 
    - lib/app/core/assets/images/

## Slidy Scripts 
scripts:
  mobx: flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs
    
flutter_intl:
  enabled: true
  class_name: LocaleProvider
